/* eslint-disable */
/**
 * Generated Convex API.
 * This file is auto-generated by `npx convex dev`.
 * Do not edit manually - run `npx convex dev` to regenerate.
 */

import { anyApi, componentsGeneric } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunc = useQuery(api.myModule.myFunction);
 * ```
 */
export const api: any = anyApi;
export const internal: any = anyApi;
export const components: any = componentsGeneric();
