/* eslint-disable */
/**
 * Generated Convex server functions.
 * This file is auto-generated by `npx convex dev`.
 * Do not edit manually - run `npx convex dev` to regenerate.
 */

import {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
  internalQueryGeneric,
  internalMutationGeneric,
  internalActionGeneric,
} from "convex/server";
import type {
  QueryBuilder,
  MutationBuilder,
  ActionBuilder,
} from "convex/server";
import type { DataModel } from "./dataModel";

export const query = queryGeneric as unknown as QueryBuilder<DataModel, "public">;
export const mutation = mutationGeneric as unknown as MutationBuilder<DataModel, "public">;
export const action = actionGeneric as unknown as ActionBuilder<DataModel, "public">;
export const internalQuery = internalQueryGeneric as unknown as QueryBuilder<DataModel, "internal">;
export const internalMutation = internalMutationGeneric as unknown as MutationBuilder<DataModel, "internal">;
export const internalAction = internalActionGeneric as unknown as ActionBuilder<DataModel, "internal">;
